[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'crusoexia/vim-monokai'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'murmur'
  let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
	let NERDSpaceDelims = 1
	let NERDCreateDefaultMappings = 0
	nmap ,, <Plug>NERDCommenterToggle
	vmap ,, <Plug>NERDCommenterToggle
'''
