[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'crusoexia/vim-monokai'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'murmur'
  let g:airline#extensions#tabline#enables = 1
'''

