[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'crusoexia/vim-monokai'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'murmur'
  " let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
	let NERDSpaceDelims = 1
	let NERDCreateDefaultMappings = 0
	nmap ,, <Plug>NERDCommenterToggle
	vmap ,, <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = "osyo-manga/vim-precious"

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'ncm2/ncm2'
depends  = ['ncm2-path', 'ncm2-bufword']
hook_add = '''
	autocmd BufEnter * call ncm2#enable_for_buffer()
	set completeopt=noinsert,menuone,noselect
	inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
	inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'ncm2/ncm2-bufword'

[[plugins]]
repo = 'ncm2/ncm2-path'

[[plugins]]
repo = 'tpope/vim-surround'
